# Generated by Django 3.2.5 on 2021-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subname',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
