# Generated by Django 3.2.5 on 2021-08-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20210813_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members_number',
        ),
    ]
